export const environment = {
  production: true,
  // base_url:"http://111.118.248.220:8222/admin/",
  // apiUrl:"http://111.118.248.220:8222/nail_app/index.php/api/V_1/",
  base_url: "http://10.10.3.26:8222/admin/",
  apiUrl: "http://10.10.3.26:8222/nail_app/index.php/api/V_1/",
  google_map_api_key: "AIzaSyBLey8ESni-1AM0QuerNuawFP51Lot8xXg",
  authorization: "Basic YWRtaW46MTIzNDU2",
  contentType: "application/json",
  apiEndPoints: {
    login:"storeAuth/storeLogin",
    homePage:"store/homePage",
    isLoggedIn:"store/isLoggedIn",
    addStoreNews:"store/addStoreNews",
    updateStoreNews:"store/updateStoreNews",
    getStoreNews:"store/getStoreNews",
    deleteStoreNews:"store/deleteStoreNews",
    getOneStoreNews:"store/getOneStoreNews",
    getStoreRewards:"store/getStoreRewards",
    updateUserProfile:"store/updateUserProfile",
    changePassword:"store/changePassword",
    addStoreRewards:"store/addStoreRewards",
    getOneStoreReward:"store/getOneStoreReward",
    updateStoreRewards:"store/updateStoreRewards",
    deleteStoreReward:"store/deleteStoreReward",
    updateStoreHours:"store/updateStoreHours",
    uploadStoreLogo:"store/uploadStoreLogo",
    uploadStoreMenu:"store/uploadStoreMenu",
    updateRewardSettings:"store/updateRewardSettings",
    updateAppearanceSettings:"store/updateAppearanceSettings",
    customerList:"store/customerList",
    customerDetail:"store/customerDetail",
    redeemReward:"store/redeemReward",
    customerTransaction:"store/customerTransaction",
    updateStoreInformation:"store/updateStoreInformation",

  }
};