export const environment = {
  version: "1.0.3",
  production: true,
  base_url: "https://nailsalon.nailrewards.com/",
  apiUrl: "https://nailrewards.com/webservice/index.php/api/V_1/",
  google_map_api_key: "AIzaSyBLey8ESni-1AM0QuerNuawFP51Lot8xXg",
  authorization: "Basic YWRtaW46MTIzNDU2",
  contentType: "application/json",
  apiEndPoints: {
    login:"storeAuth/storeLogin",
    forgetPasswordUsingEmailOTP:"storeAuth/forgetPasswordUsingEmailOTP",
    verifyPasswordOTP:"storeAuth/verifyPasswordOTP",
    resetPasswordUsingEmailOTP:"storeAuth/resetPasswordUsingEmailOTP",
    getStoreDetials:"storeAuth/getStoreDetials",
    getCustomerDetials:"storeAuth/getCustomerDetials",
    addReward:"storeAuth/addPointTransaction",
    redeemstoreAuthReward:"storeAuth/redeemReward",
    storePinUpdate:"store/storepinUpdate",

    homePage:"store/homePage",
    isLoggedIn:"store/isLoggedIn",
    addStoreNews:"store/addStoreNews",
    updateStoreNews:"store/updateStoreNews",
    getStoreNews:"store/getStoreNews",
    deleteStoreNews:"store/deleteStoreNews",
    getOneStoreNews:"store/getOneStoreNews",
    getStoreRewards:"store/getStoreRewards",
    updateUserProfile:"store/updateUserProfile",
    changePassword:"store/changePassword",
    addStoreRewards:"store/addStoreRewards",
    getOneStoreReward:"store/getOneStoreReward",
    updateStoreRewards:"store/updateStoreRewards",
    deleteStoreReward:"store/deleteStoreReward",
    updateStoreHours:"store/updateStoreHours",
    uploadStoreLogo:"store/uploadStoreLogo",
    uploadStoreMenu:"store/uploadStoreMenu",
    updateRewardSettings:"store/updateRewardSettings",
    updateAppearanceSettings:"store/updateAppearanceSettings",
    customerList:"store/customerList",
    globleCustomerList:"store/globleCustomerList",
    customerDetail:"store/customerDetail",
    redeemReward:"store/redeemReward",
    customerTransaction:"store/customerTransaction",
    updateStoreInformation:"store/updateStoreInformation",
    updateSocialLinks:"store/updateSocialLinks",
    sendNotification:"store/sendNotification",
    templateFilesForPanels:"store/templateFilesForPanels",
    autoNotificationList:"store/autoNotificationList",
    deleteAutoNotificaiton:"store/deleteAutoNotificaiton",
    autoNotification:"store/autoNotification",
    storeAverageRating:"store/storeAverageRating",
    getRecentRating:"store/getRecentRating",

  }
};